# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

jobs:
- job: build
  pool:
    vmImage: 'Ubuntu 16.04'

  variables:
    imageName: 'your-container-image-name:$(build.buildId)'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      goals: 'clean test package'
      testResultsFormat: 'JUnit' # Options: JUnit, NUnit, VSTest, xUnit
      testResultsFiles: '**/TEST-*.xml' 

- job: docker_upload
  dependsOn: build
  condition: succeeded('build')
  
  pool:
    vmImage: 'Ubuntu 16.04'

  variables:
    imageName: 'your-container-image-name:$(build.buildId)'
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      goals: 'package'
      options: '-P docker-build'
