version: 2
jobs:
  Build-Compile:
    working_directory: ~/coffee-shop
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout
      - restore_cache:
          key: coffee-shop-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline    
      - save_cache:
          paths:
            - ~/.m2
          key: coffee-shop-{{ checksum "pom.xml" }}
      - run: mvn compile
      - persist_to_workspace:
          root: . # Persist current working directory
          paths: ./* # Glob. Will persist everything in folder
      
  Build-Test:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - attach_workspace:
          at: .
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports

  Build-Documentation:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - attach_workspace:
          at: .
      - run: mvn site

workflows:
  version: 2
  Approved-Build:
    jobs:
      - Build-Compile
      - Hold-For-Approval:
          type: approval
          requires:
            - Build-Compile
      - Build-Test:
          requires:
            - Hold-For-Approval

  Quick-Build:
    jobs:
      - Build-Compile

  Documentation-Build:
    jobs:
      - Build-Compile
      - Build-Documentation:
          requires:
            - Build-Compile

